// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
import 'firebase_options.dart';
import 'package:firebase_core/firebase_core.dart';

Future<void> initializeFirebase() async {
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
}

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDOqloOwRL3W5y7uMXhUzeiz3KkUAK3nM',
    appId: '1:712964741137:web:58f76d2b78e9944b3879b0',
    messagingSenderId: '712964741137',
    projectId: 'vitacure-9894d',
    authDomain: 'vitacure-9894d.firebaseapp.com',
    storageBucket: 'vitacure-9894d.firebasestorage.app',
    measurementId: 'G-WLNL6W3QZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFYLe3evlAwaALlMRSTgxIllelqEXsZmg',
    appId: '1:712964741137:android:d1d817e1b7c57b7a3879b0',
    messagingSenderId: '712964741137',
    projectId: 'vitacure-9894d',
    storageBucket: 'vitacure-9894d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHjvaTN-HXUVMfwWa9Qa5QfjEdSL2RGvQ',
    appId: '1:712964741137:ios:d9c144b396fefaa53879b0',
    messagingSenderId: '712964741137',
    projectId: 'vitacure-9894d',
    storageBucket: 'vitacure-9894d.firebasestorage.app',
    iosBundleId: 'com.example.flutterUreekaphase2Kesehatan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDOqloOwRL3W5y7uMXhUzeiz3KkUAK3nM',
    appId: '1:712964741137:web:72848975626bc17d3879b0',
    messagingSenderId: '712964741137',
    projectId: 'vitacure-9894d',
    authDomain: 'vitacure-9894d.firebaseapp.com',
    storageBucket: 'vitacure-9894d.firebasestorage.app',
    measurementId: 'G-L6Y7PXF3TW',
  );
}
